version: "3"
services:
  node:
    restart: always
    entrypoint: [sh, ./docker-entry.sh, "mysql_db", "${DB_PORT}"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/pm2
    networks:
      - authservice-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    restart: always
    command: --innodb_use_native_aio=0
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOSTNAME}
    networks:
      - authservice-network

networks:
  authservice-network:
    driver: bridge
