version: "3"
services:
  node:
    restart: always
    entrypoint: [sh, ./docker-entry.sh, "auth_mysql_db", "3306"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/pm2
    networks:
      - authservice-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - auth_mysql_db

  auth_mysql_db:
    image: mysql:5.7
    restart: always
    command: --innodb_use_native_aio=0
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOSTNAME}
    networks:
      - authservice-network

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - authservice-network
    environment:
      PORT: ${WEB_PORT}
      PROXY_URL: http://node:${PORT}
      WEB_PORT: ${WEB_PORT}
      WEB_EXPOSED_PORT: ${WEB_EXPOSED_PORT}
      HOSTNAME: ${HOST_HOSTNAME}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - ${WEB_EXPOSED_PORT}:${WEB_EXPOSED_PORT}
    volumes:
      - ${CERT_PATH}:/etc/ssl
    depends_on:
      - auth_mysql_db
    entrypoint: [sh, /etc/nginx/run_nginx.sh, "${HOST_HOSTNAME}"]  

networks:
  authservice-network:
    driver: bridge
