export const Constants = {
	ROLE_SELECTED: 'ROLE_SELECTED',
	USER_SELECTED: 'USER_SELECTED',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	LOGOUT: 'LOGOUT',
	LOGIN_FAIL_INSUFFICIENT_PRIVILEGE: 'LOGIN_FAIL_INSUFFICIENT_PRIVILEGE'
}